version: "3"

# サービス設定
services:

    # mysql
    db:
        image: mysql:8
        volumes:
        - /var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=struts2-demo
        - MYSQL_USER=struts2-demo
        - MYSQL_PASSWORD=struts2-demo

    # tomcat
    web:
        image: asahinadev/tomcat9:oraclejdk11
        volumes:
        - ./context.xml:/usr/local/tomcat/current/conf/context.xml:ro
        - ./mysql-connector-java-8.0.20.jar:/usr/local/tomcat/current/lib/mysql-connector-java-8.0.20.jar:ro
        - ../build/libs/struts2-example.war:/usr/local/tomcat/current/webapps/struts2-example.war:ro
        ports:
        - 40000:8080
        depends_on:
        - db
