version: "3"

# サービス設定
services:

    # mysql(mariadb)
    db:
        container_name: struts2_example_db      
        image: mysql:8
        volumes:
        - /var/lib/mysql
        ports:
        - 40010:3306
        - 40011:33060
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=struts2-demo
        - MYSQL_USER=struts2-demo
        - MYSQL_PASSWORD=struts2-demo

    # httpd+tomcat
    web:
        container_name: struts2_example_web      
        image: tomcat:9.0.34-jdk14-openjdk-oracle
        ports:
        - 40000:8080
        - 40001:8009
        - 40002:8005
        links:
        - db
